### PR TITLE
Mp 2048 fib

### PR DESCRIPTION
**Pull request by sritej-reddy**
deleted prev branch because i have added unnecessary files
This is new branch

### CODE REVIEW

**Comment by krushiraj** [comment]
You can use specific command instead of deleting the branch

Read about git reset and git revert. Try to learn git commands and their usage while you're working on this. It will be easier to learn like this practically instead of learning it via a course. That will definitely help you in the future.

**Review by krushiraj — COMMENTED** [review]
I didn't get time to test and see if the Mini Project is working fine. What I can suggest is that you test it yourself for edge cases. Ask your friends both tech related and not tech related guys to play it and get feedback and try to work on it or at least think of their feedback and see where you went wrong and how can you fix those.

**Comment by krushiraj** [comment]
If you think no more changes are required just let me know here then we can merge this to master.

**Comment by sritej-reddy** [comment]
Ok i'll test with all type of test cases. One it seems to be fine i'll let
you know

**Comment by sritej-reddy** [comment]
Game is ready to be merged

**Comment by sritej-reddy** [comment]
closes #25

**Pull request merged**
